[package]
name = "process_mining"
version = "0.1.6"
edition = "2021"
license = "MIT OR Apache-2.0"
homepage = "https://github.com/aarkue/rust-bridge-process-mining"
description = "Basic Process Mining data structures, functions and co."
repository = "https://github.com/aarkue/rust-bridge-process-mining"
readme = "README.md"
keywords = ["process-mining"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rayon = "1.7.0"
serde_json = "1.0.105"
serde = {version = "1.0.188", features = ["derive"]}
chrono = {version = "0.4.29", features = ["serde"] }
uuid = {version = "1.4.1", features = ["v4", "serde"]}
quick-xml = {version = "0.31.0"}
flate2 = "1.0"